# Configuración datasource H2 para testing
spring.datasource.url=jdbc:h2:mem:petconnect-test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=1234

# Configuración JPA para testing
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Desactivar consola H2 en tests
spring.h2.console.enabled=false

# Configuración JWT para testing
jwt.secret=petconnect-test-secret
jwt.expiration-ms=3600000
